# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
#- task: NuGetToolInstaller@1

#- task: NuGetCommand@2
#  inputs:
#    restoreSolution: '$(solution)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Checking .NET version"
      
      $release = (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full").Release
      switch ($release) {
          { $_ -ge 533325 } { "Installed: .NET Framework 4.8.1 or later"; break }
          { $_ -ge 528040 } { "Installed: .NET Framework 4.8"; break }
          default { "Installed: Version earlier than 4.8 or not installed" }
      }
    
- task: CmdLine@2
  displayName: Install SSRS VSIX extension
  inputs:
    script: |
      echo Write your commands here
      
      echo Downloading MS Report Projects for Visual Studio 2022
      
      curl -L --output MicrosoftReportProjectsforVisualStudio2022.vsix --create-dirs --url https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ProBITools/vsextensions/MicrosoftReportProjectsforVisualStudio2022/latest/vspackage
      
      echo Install the VSIX extension
      
      "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\VSIXInstaller.exe" /quiet MicrosoftReportProjectsforVisualStudio2022.vsix 
      
- task: CmdLine@2
  displayName: Download and install .NET Framework 4.8
  inputs:
    script: |
      echo Downloading .NET Framework 4.8...
      
      curl.exe -L --output .\DotNet48\NDP48-x86-x64-AllOS-ENU.exe https://go.microsoft.com/fwlink/?linkid=2088631

      echo list downloaded file
      cd DotNet48
      dir
      
      echo Start Installation
      
      NDP48-x86-x64-AllOS-ENU.exe /q /norestart

- task: PowerShell@2
  displayName: Check .NET version installed
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Checking .NET version"
      
      $release = (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full").Release
      switch ($release) {
          { $_ -ge 533325 } { "Installed: .NET Framework 4.8.1 or later"; break }
          { $_ -ge 528040 } { "Installed: .NET Framework 4.8"; break }
          default { "Installed: Version earlier than 4.8 or not installed" }
      }
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
